### ISSUE TITLE
Commit v1.0

### ISSUE THREAD

**Issue by AlexFaraino** [fabelier/Doorbell#17]
I think this could be the v1.0 release (once the p/r about the name is merged).

**Comment by gturri** [comment]
If we want version tags, now seems to be a good time, indeed.

I currently have in mind only the feature you suggested about providing the QR code.
Work is in progress (https://github.com/gturri/Doorbell/tree/qr_generator) but won't be over soon, and isn't really needed for v1

Btw, what about a v1.0.0, to follow http://semver.org/ guidelines?
Admittedly we're unlikely to ever change the first digit, but on the other hand, tagging a v2.0 as soon as we add the qr generation would seem a bit weird.

Anyway, just thinking out loud. Do as you will.
