### ISSUE TITLE
Play a different tune when disconnected

### ISSUE THREAD

**Issue by gturri** [fabelier/Doorbell#19]
What about playing a tune different than he ringing one, to warn that the host page is disconnected?

Advantage would be that when it happens, you instantaneously knows no one is at the door, without having to either look at the page, or wait for 10s to see if it loops.

**Comment by AlexFaraino** [comment]
I agree. We could use something simple like : http://lasonotheque.org/detail-0457-electrocardiogramme_60_hz.html
We also should change the ringing sound, as it have a copyright.
What do you think ?

**Comment by gturri** [comment]
This electrocardiogramme seems rather aggressive to me. I'll try to see if I can suggest something else.

Regarding our current sound, indeed, we should use something with a free license instead

**Comment by gturri** [comment]
Closing: this probably doesn't make sense any more
