### ISSUE TITLE
Add automated non reg tests

### ISSUE THREAD

**Issue by gturri** [fabelier/Doorbell#8]
It's a rather simple application. However, it's easy to break a feature without noticing it.

I believe we could either (or both):
- unit test the javascript (but it would likely require to decouple the JS and the html)
- do end to end test, eg using selenium

**Comment by AlexFaraino** [comment]
As we only have to add the password feature, I'm not sure it's necessary.

**Comment by gturri** [comment]
Admittedly, I don't currently have much features in mind for the short term.

However, I can't help thinking we (or someone else) may want to, at some point in the future, dev on it again.

**Comment by gturri** [comment]
Closing: this issue probably doesn't make sense anymore
