### ISSUE TITLE
QR code rather than URL?

### ISSUE THREAD

**Issue by gturri** [fabelier/Doorbell#9]
A suggestion of a friend of mine: rather than asking the visitors to navigate to a url, to potentially type a password on a smartphone, and to click a button, what about letting them scan a QR code?

The current solution has the advantage that the host doesn't need to stick a QR code on the door.
But if we're ready to put a post-it with tonight's code, it wouldn't be more difficult to add a QR code.
Anyway, I believe we could easily keep the two interfaces to get the best of both worlds.

In practice, I guess we just need to change index.js so that it accept a 3rd type of url (say qrcode.hml?password=xxx). When this url is requested, it sends a message to the host, and serves the client with a page which can handle "acknowledge messages.

What do you think?

**Comment by AlexFaraino** [comment]
That could help. We won't use it much because we don't have a printer, though.
Do you want to integrate a QRCode Generator to the code (like https://www.npmjs.org/package/qrcode)?
If so, maybe we also should add a link on the monitor page to generate the code in a dedicated page.

**Comment by gturri** [comment]
Closing: this probably doesn't make sense any more
